#
# Makefile for the kernel micom device interfaces.
#
obj-$(CONFIG_AR_WT61P807)	+= ar-wt61p807.o
obj-$(CONFIG_ISP_WT61P807)	+= isp-wt61p807.o
obj-$(CONFIG_BRIGHTNESS_SENSOR_WT61P807)	+= bsensor-wt61p807.o
obj-$(CONFIG_ONTIMER_WT61P807)	+= ontimer-wt61p807.o
obj-$(CONFIG_SYSTEM_WT61P807)	+= system-wt61p807.o
obj-$(CONFIG_CEC_WT61P807) += cec-wt61p807.o
obj-$(CONFIG_MSG_WT61P807) += msg-wt61p807.o
