#Add for AGENT
obj-y += agent_error.o agent_packet.o agent_core.o agent_cm.o
# Add for thread profiler to agent.
obj-$(CONFIG_KDEBUGD_THREAD_PROFILER) += kdbg_thread_profiler.o

#Add for rb
obj-y += ringbuffer.o
obj-y += ringbuffer_init.o
obj-y += mmap_kernel.o
