/*
 * tvis_agent_cmds.h
 *
 * Copyright (C) 2012 Samsung Electronics
 *
 * NOTE:
 *
 */
#ifndef _TVIS_AGENT_CMDS_H
#define _TVIS_AGENT_CMDS_H

enum tvis_agent_kdbg_cm_event{
	START,
	STOP
};

/* kdebugd commands */
enum tvis_agent_kdbg_cmds {

	KDBG_CMD_START_KDEBUGD = 0x00000001,
	KDBG_CMD_STOP_KDEBUGD,
	KDBG_CMD_GET_THREAD_INFO,
	KDBG_CMD_GET_MEM_USAGE,
	KDBG_CMD_CM_CPU_USAGE,
	KDBG_CMD_CM_THREAD_USAGE,
	KDBG_CMD_CM_PROCESS_USAGE,
	KDBG_CMD_CM_PHY_MEM_USAGE,
	KDBG_CMD_GET_VIRT_MEM_USAGE,
	KDBG_CMD_CM_PMU_CNTR = 0x0000000A,
	KDBG_CMD_CM_DISK_USAGE,
	KDBG_CMD_CM_NET_USAGE,
	KDBG_CMD_AOP_GET_SRC,
	KDBG_CMD_AOP_SET_SRC,
	KDBG_CMD_AOP_START,
	KDBG_CMD_AOP_STOP = 0x00000010,
	KDBG_CMD_AOP_DATA,
	KDBG_CMD_AOP_DATA_END,
	KDBG_CMD_GET_THREAD_INFO_DETAIL,
	KDBG_CMD_START_THREAD_PROFILE_INFO,
	KDBG_CMD_THREAD_PROFILE_INFO,
	KDBG_CMD_STOP_THREAD_PROFILE_INFO,
	KDBG_CMD_USER_BACKTRACE,
	KDBG_CMD_CM_MEM_INFO,
	KDBG_CMD_MAX = 0x00000080,
};

#endif
